import {
  createContext,
  useContext,
  useEffect,
  useLayoutEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";
import { useErrorToast } from "./ErrorToast";
import { localizedCopy, setActiveLanguage, type Language } from "../i18n";

export { localizedCopy, type Language } from "../i18n";

export const LANGUAGE_STORAGE_KEY = "token-station-language";
export const LANGUAGE_PREFERENCE_VERSION_KEY = "token-station-language-preference-version";
const LANGUAGE_PREFERENCE_VERSION = "2";

const messages = {
  "zh-CN": {
    "nav.main": "主导航",
    "nav.homeLabel": "Token Station 主页",
    "nav.home": "主页",
    "nav.scanning": "扫描中",
    "nav.rescan": "重新扫描",
    "nav.usage": "用量",
    "nav.settings": "设置",
    "nav.addProvider": "添加供应商",
    "serve.unknown": "运行态未知",
    "serve.running": "代理运行中",
    "serve.starting": "正在启动",
    "serve.stopping": "正在停止",
    "serve.retry": "重试启动",
    "serve.startProxy": "启动代理",
    "serve.agent": "Agent",
    "serve.connected": "已连接",
    "serve.disconnected": "未连接",
    "serve.stop": "停止",
    "serve.cancel": "取消",
    "serve.stoppingShort": "停止中",
    "serve.start": "启动",
    "settings.controlRoom": "CONTROL ROOM",
    "settings.title": "设置",
    "settings.navLabel": "设置分类",
    "settings.general": "代理",
    "settings.generalHint": "代理、指标和出站策略",
    "settings.apiKey": "API Key",
    "settings.apiKeyHint": "本机 Agent 访问凭据",
    "settings.agentVisibility": "Agent 显示",
    "settings.agentVisibilityHint": "主页 Agent 列表",
    "settings.router": "路由表",
    "settings.routerHint": "只读决策结构",
    "settings.plugins": "插件",
    "settings.pluginsHint": "已加载的能力",
    "settings.appearance": "外观",
    "settings.appearanceHint": "明暗主题",
    "settings.language": "语言",
    "settings.languageHint": "界面显示语言",
    "settings.about": "关于",
    "settings.aboutHint": "版本与更新",
    "language.eyebrow": "LANGUAGE",
    "language.title": "界面语言",
    "language.description": "切换后立即应用到整个界面，无需重启。",
    "language.groupLabel": "界面语言",
    "language.zhCNHint": "简体中文界面",
    "language.zhTWHint": "繁體中文介面",
    "language.enHint": "English interface",
    "language.jaHint": "日本語インターフェース",
    "appearance.eyebrow": "APPEARANCE",
    "appearance.title": "外观",
    "appearance.description": "主题会同步应用到主页、Agent、用量和设置中的所有页面。",
    "appearance.groupLabel": "界面主题",
    "appearance.light": "浅色",
    "appearance.lightHint": "稳定使用明亮界面",
    "appearance.dark": "深色",
    "appearance.darkHint": "稳定使用暗色界面",
    "appearance.system": "跟随系统",
    "appearance.systemHint": "当前系统为{theme}",
    "appearance.systemLight": "浅色",
    "appearance.systemDark": "深色",
    "agentVisibility.title": "Agent 显示",
    "agentVisibility.description": "选择显示在主页列表中的 Agent；未检测到的 Agent 默认关闭。",
    "agentVisibility.count": "{visible} / {total} 已显示",
    "agentVisibility.groupLabel": "Agent 显示选项",
    "agentVisibility.empty": "当前 Registry 没有可显示的 Agent。",
    "key.eyebrow": "LOCAL AUTH",
    "key.title": "虚拟 API Key",
    "key.description": "供本机 Agent 访问 Token Station。默认隐藏，复制时无需显示明文。",
    "key.authTitle": "API Key 鉴权",
    "key.authSettingsDescription": "控制本机 Agent 请求是否必须携带虚拟 API Key。",
    "key.generated": "已生成",
    "key.proxyStopped": "代理未运行",
    "key.ariaLabel": "虚拟 API Key",
    "key.startToGenerate": "启动代理后生成",
    "key.hide": "隐藏",
    "key.show": "显示 15 秒",
    "key.copied": "已复制",
    "key.copy": "复制",
    "general.title": "代理与数据",
    "general.description": "配置本地指标和显式出站策略。",
    "general.saved": "已保存",
    "general.savedRestart": "已保存 · 重启代理后生效",
    "general.auth": "虚拟 Key 鉴权",
    "general.authDescription": "开启后 serve 首启生成虚拟 Key，所有请求须带 Key。关掉则回环端口无鉴权，仅建议本机可信环境。",
    "general.egress": "出站策略",
    "general.egressDescription": "显式选择直连、HTTP CONNECT 或 SOCKS5；不会读取系统 HTTP_PROXY / ALL_PROXY。",
    "general.egressMode": "出口模式",
    "general.direct": "直连",
    "general.proxyUrl": "代理 URL",
    "general.noProxy": "no_proxy",
    "general.proxyUsername": "代理用户名",
    "general.authSlot": "认证槽",
    "general.authSlotLabel": "代理认证槽",
    "general.credentialCommand": "写入凭据：token-station-cli key set egress-proxy {slot}",
    "general.routeSummary": "Provider 请求、模型目录与健康探测：{route}；更新检查固定直连。每次 3xx 仍拒绝跟随，跨主机不会转发原 Authorization。",
    "general.resolvedRoutes": "实际出口解析",
    "general.pendingProxy": "待填写代理",
    "general.matchedNoProxy": "命中 no_proxy",
    "general.metrics": "本地指标",
    "general.metricsDescription": "把每次请求的元数据（延迟/token/落档，永不含 prompt 内容）写入本地 SQLite，供「用量」页聚合。",
    "general.save": "保存",
    "general.restartHint": "代理运行中——保存后需重启代理才生效",
    "general.listen": "监听地址",
    "general.dataDir": "数据目录",
    "general.pluginsDir": "插件目录",
    "general.adapter": "入站适配器",
    "general.coreVersion": "内核版本",
    "runtime.title": "运行信息",
    "runtime.description": "查看当前监听地址、数据位置和已加载的运行组件。",
    "about.title": "关于 · 更新",
    "about.description": "只在你主动点击时匿名检查最新发布。签名校验通过后可在 App 内下载、安装并重启。",
    "about.productDescription": "本机 AI Agent 的模型请求路由站。",
    "about.versionGroup": "应用版本",
    "about.source": "GitHub",
    "about.releases": "更新日志",
    "about.trustTitle": "更新如何抵达本机",
    "about.trustDescription": "更新链路保持显式、可验证，并尽量减少对本地请求的影响。",
    "about.onDemandTitle": "按需检查",
    "about.onDemandDescription": "只有点击检查后才匿名访问发布服务。",
    "about.signedTitle": "签名验证",
    "about.signedDescription": "下载包必须通过内置公钥验证后才能安装。",
    "about.gatewayTitle": "平稳交接",
    "about.gatewayDescription": "安装前短暂停止网关并排空在途请求，然后自动重启。",
    "about.currentVersion": "当前版本",
    "about.newVersion": "有新版本 {latest}（当前 {current}）。",
    "about.latest": "已是最新（{current}，最新发布 {latest}）。",
    "about.copied": "已复制",
    "about.copyLink": "复制链接",
    "about.checking": "检查中…",
    "about.check": "检查更新",
    "about.updateFound": "发现新版本 {version}",
    "about.releaseDate": "发布日期：{date}",
    "about.installVersion": "下载并更新到 {version}",
    "about.installing": "正在验证并安装…",
    "about.downloaded": "已下载 {percent}%",
    "about.downloadedBytes": "已下载 {downloaded} 字节",
    "about.downloadProgress": "更新包下载进度",
    "about.restarting": "更新完成，正在重启…",
    "about.confirmTitle": "安装应用更新？",
    "about.confirmDescription": "更新包会先完成签名校验。进入最终安装时，本地网关会短暂停止并排空在途请求，随后 App 自动重启。",
    "about.cancel": "取消",
    "about.confirmInstall": "确认更新并重启",
    "plugins.title": "插件",
    "plugins.description": "provider / agent 适配器都是 WASM 沙箱（无网络、拿不到明文 Key）。安装/开发走 CLI，这里只读展示。",
    "plugins.directory": "插件目录",
    "plugins.adapter": "入站适配器",
    "plugins.dialects": "支持方言",
    "plugins.none": "无",
    "plugins.empty": "(空)",
    "plugins.refresh": "刷新",
    "plugins.installHint": "安装：CLI `token-station plugin install <路径>`",
    "router.loading": "加载中…",
    "router.unconfigured": "— 未配 —",
    "router.title": "路由表 · 四层",
    "router.description": "每个请求按此顺序短路命中：命中即停。第 3 层会统计整段对话的长度、轮数、代码块和能力要求；难度词只看最后一条用户消息，避免历史重复内容把所有后续请求永久顶到高档。",
    "router.rules": "规则（硬匹配）",
    "router.noRules": "无规则。规则用于「某条件强制走某池」，当前留空。",
    "router.hints": "提示路由（agent Hint）",
    "router.noHints": "无提示路由。入站适配器给出 step_type 等 Hint 时在此分流，当前留空。",
    "router.bands": "启发式分档",
    "router.threshold": "阈值 {value}",
    "router.noBands": "还没配档。去「主页」给三档各选供应商 + 模型。",
    "router.score": "分数 ≥",
    "router.pool": "档池",
    "router.target": "落到",
    "router.default": "默认兜底",
    "router.contextWindow": "假定上下文窗",
  },
  "zh-TW": {
    "nav.main": "主導覽",
    "nav.homeLabel": "Token Station 首頁",
    "nav.home": "首頁",
    "nav.scanning": "掃描中",
    "nav.rescan": "重新掃描",
    "nav.usage": "用量",
    "nav.settings": "設定",
    "nav.addProvider": "新增供應商",
    "serve.unknown": "執行狀態未知",
    "serve.running": "代理執行中",
    "serve.starting": "正在啟動",
    "serve.stopping": "正在停止",
    "serve.retry": "重試啟動",
    "serve.startProxy": "啟動代理",
    "serve.agent": "Agent",
    "serve.connected": "已連線",
    "serve.disconnected": "未連線",
    "serve.stop": "停止",
    "serve.cancel": "取消",
    "serve.stoppingShort": "停止中",
    "serve.start": "啟動",
    "settings.controlRoom": "CONTROL ROOM",
    "settings.title": "設定",
    "settings.navLabel": "設定分類",
    "settings.general": "代理",
    "settings.generalHint": "代理、指標與出站策略",
    "settings.apiKey": "API Key",
    "settings.apiKeyHint": "本機 Agent 存取憑證",
    "settings.agentVisibility": "Agent 顯示",
    "settings.agentVisibilityHint": "首頁 Agent 列表",
    "settings.router": "路由表",
    "settings.routerHint": "唯讀決策結構",
    "settings.plugins": "外掛",
    "settings.pluginsHint": "已載入的能力",
    "settings.appearance": "外觀",
    "settings.appearanceHint": "明暗主題",
    "settings.language": "語言",
    "settings.languageHint": "介面顯示語言",
    "settings.about": "關於",
    "settings.aboutHint": "版本與更新",
    "language.eyebrow": "LANGUAGE",
    "language.title": "介面語言",
    "language.description": "切換後會立即套用到整個介面，無需重新啟動。",
    "language.groupLabel": "介面語言",
    "language.zhCNHint": "简体中文界面",
    "language.zhTWHint": "繁體中文介面",
    "language.enHint": "English interface",
    "language.jaHint": "日本語インターフェース",
    "appearance.eyebrow": "APPEARANCE",
    "appearance.title": "外觀",
    "appearance.description": "主題會同步套用到首頁、Agent、用量與設定中的所有頁面。",
    "appearance.groupLabel": "介面主題",
    "appearance.light": "淺色",
    "appearance.lightHint": "固定使用明亮介面",
    "appearance.dark": "深色",
    "appearance.darkHint": "固定使用深色介面",
    "appearance.system": "跟隨系統",
    "appearance.systemHint": "目前系統為{theme}",
    "appearance.systemLight": "淺色",
    "appearance.systemDark": "深色",
    "agentVisibility.title": "Agent 顯示",
    "agentVisibility.description": "選擇顯示在首頁列表中的 Agent；未偵測到的 Agent 預設關閉。",
    "agentVisibility.count": "{visible} / {total} 已顯示",
    "agentVisibility.groupLabel": "Agent 顯示選項",
    "agentVisibility.empty": "目前 Registry 沒有可顯示的 Agent。",
    "key.eyebrow": "LOCAL AUTH",
    "key.title": "虛擬 API Key",
    "key.description": "供本機 Agent 存取 Token Station。預設隱藏，複製時無需顯示明文。",
    "key.authTitle": "API Key 驗證",
    "key.authSettingsDescription": "控制本機 Agent 請求是否必須攜帶虛擬 API Key。",
    "key.generated": "已產生",
    "key.proxyStopped": "代理未執行",
    "key.ariaLabel": "虛擬 API Key",
    "key.startToGenerate": "啟動代理後產生",
    "key.hide": "隱藏",
    "key.show": "顯示 15 秒",
    "key.copied": "已複製",
    "key.copy": "複製",
    "general.title": "代理與資料",
    "general.description": "設定本機指標與明確的出站策略。",
    "general.saved": "已儲存",
    "general.savedRestart": "已儲存 · 重新啟動代理後生效",
    "general.auth": "虛擬 Key 驗證",
    "general.authDescription": "開啟後，serve 首次啟動會產生虛擬 Key，所有請求都必須攜帶 Key。關閉後回環連接埠不驗證，僅建議用於可信任的本機環境。",
    "general.egress": "出站策略",
    "general.egressDescription": "明確選擇直連、HTTP CONNECT 或 SOCKS5；不會讀取系統 HTTP_PROXY / ALL_PROXY。",
    "general.egressMode": "出口模式",
    "general.direct": "直連",
    "general.proxyUrl": "代理 URL",
    "general.noProxy": "no_proxy",
    "general.proxyUsername": "代理使用者名稱",
    "general.authSlot": "驗證槽",
    "general.authSlotLabel": "代理驗證槽",
    "general.credentialCommand": "寫入憑證：token-station-cli key set egress-proxy {slot}",
    "general.routeSummary": "Provider 請求、模型目錄與健康探測：{route}；更新檢查固定直連。每次 3xx 仍拒絕跟隨，跨主機不會轉送原 Authorization。",
    "general.resolvedRoutes": "實際出口解析",
    "general.pendingProxy": "待填寫代理",
    "general.matchedNoProxy": "符合 no_proxy",
    "general.metrics": "本機指標",
    "general.metricsDescription": "將每次請求的中繼資料（延遲/token/歸檔，絕不包含 prompt 內容）寫入本機 SQLite，供「用量」頁彙總。",
    "general.save": "儲存",
    "general.restartHint": "代理執行中——儲存後需重新啟動代理才會生效",
    "general.listen": "監聽位址",
    "general.dataDir": "資料目錄",
    "general.pluginsDir": "外掛目錄",
    "general.adapter": "入站適配器",
    "general.coreVersion": "核心版本",
    "runtime.title": "執行資訊",
    "runtime.description": "查看目前的監聽位址、資料位置與已載入的執行元件。",
    "about.title": "關於 · 更新",
    "about.description": "只在你主動點擊時匿名檢查最新版本。簽章驗證通過後可在 App 內下載、安裝並重新啟動。",
    "about.productDescription": "本機 AI Agent 的模型請求路由站。",
    "about.versionGroup": "應用程式版本",
    "about.source": "GitHub",
    "about.releases": "更新日誌",
    "about.trustTitle": "更新如何抵達本機",
    "about.trustDescription": "更新路徑保持明確且可驗證，同時盡量減少對本機請求的影響。",
    "about.onDemandTitle": "按需檢查",
    "about.onDemandDescription": "只有在你要求檢查後，應用程式才會匿名連線至發布服務。",
    "about.signedTitle": "簽章驗證",
    "about.signedDescription": "下載項目必須通過內建公開金鑰驗證後才能安裝。",
    "about.gatewayTitle": "平穩交接",
    "about.gatewayDescription": "閘道會短暫停止並排空處理中的請求，然後應用程式會重新啟動。",
    "about.currentVersion": "目前版本",
    "about.newVersion": "有新版本 {latest}（目前 {current}）。",
    "about.latest": "已是最新版本（{current}，最新發布 {latest}）。",
    "about.copied": "已複製",
    "about.copyLink": "複製連結",
    "about.checking": "檢查中…",
    "about.check": "檢查更新",
    "about.updateFound": "發現新版本 {version}",
    "about.releaseDate": "發布日期：{date}",
    "about.installVersion": "下載並更新到 {version}",
    "about.installing": "正在驗證並安裝…",
    "about.downloaded": "已下載 {percent}%",
    "about.downloadedBytes": "已下載 {downloaded} 位元組",
    "about.downloadProgress": "更新套件下載進度",
    "about.restarting": "更新完成，正在重新啟動…",
    "about.confirmTitle": "安裝應用程式更新？",
    "about.confirmDescription": "更新包會先完成簽章驗證。進入最終安裝時，本機閘道會短暫停止並排空處理中的請求，隨後 App 自動重新啟動。",
    "about.cancel": "取消",
    "about.confirmInstall": "確認更新並重新啟動",
    "plugins.title": "外掛",
    "plugins.description": "provider / agent 適配器皆位於 WASM 沙箱（無網路、無法取得明文 Key）。安裝與開發使用 CLI，此處僅供唯讀檢視。",
    "plugins.directory": "外掛目錄",
    "plugins.adapter": "入站適配器",
    "plugins.dialects": "支援方言",
    "plugins.none": "無",
    "plugins.empty": "（空）",
    "plugins.refresh": "重新整理",
    "plugins.installHint": "安裝：CLI `token-station plugin install <路徑>`",
    "router.loading": "載入中…",
    "router.unconfigured": "— 未設定 —",
    "router.title": "路由表 · 四層",
    "router.description": "每個請求依此順序短路命中：命中即停止。第 3 層會統計完整對話的長度、輪數、程式碼區塊與能力要求；難度詞只看最後一則使用者訊息，避免歷史重複內容讓後續請求永久停在高層級。",
    "router.rules": "規則（硬比對）",
    "router.noRules": "沒有規則。規則用於「特定條件強制走某個池」，目前留空。",
    "router.hints": "提示路由（agent Hint）",
    "router.noHints": "沒有提示路由。入站適配器提供 step_type 等 Hint 時會在此分流，目前留空。",
    "router.bands": "啟發式分級",
    "router.threshold": "閾值 {value}",
    "router.noBands": "尚未設定分級。請到「首頁」為三個層級選擇供應商與模型。",
    "router.score": "分數 ≥",
    "router.pool": "層級池",
    "router.target": "目標",
    "router.default": "預設後備",
    "router.contextWindow": "假定上下文視窗",
  },
  en: {
    "nav.main": "Main navigation",
    "nav.homeLabel": "Token Station home",
    "nav.home": "Home",
    "nav.scanning": "Scanning",
    "nav.rescan": "Rescan",
    "nav.usage": "Usage",
    "nav.settings": "Settings",
    "nav.addProvider": "Add provider",
    "serve.unknown": "Runtime unknown",
    "serve.running": "Proxy running",
    "serve.starting": "Starting",
    "serve.stopping": "Stopping",
    "serve.retry": "Retry start",
    "serve.startProxy": "Start proxy",
    "serve.agent": "Agent",
    "serve.connected": "Connected",
    "serve.disconnected": "Disconnected",
    "serve.stop": "Stop",
    "serve.cancel": "Cancel",
    "serve.stoppingShort": "Stopping",
    "serve.start": "Start",
    "settings.controlRoom": "CONTROL ROOM",
    "settings.title": "Settings",
    "settings.navLabel": "Settings categories",
    "settings.general": "Proxy",
    "settings.generalHint": "Proxy, metrics, and egress policy",
    "settings.apiKey": "API key",
    "settings.apiKeyHint": "Local Agent access credential",
    "settings.agentVisibility": "Agent visibility",
    "settings.agentVisibilityHint": "Home Agent list",
    "settings.router": "Router",
    "settings.routerHint": "Read-only decision structure",
    "settings.plugins": "Plugins",
    "settings.pluginsHint": "Loaded capabilities",
    "settings.appearance": "Appearance",
    "settings.appearanceHint": "Light and dark themes",
    "settings.language": "Language",
    "settings.languageHint": "Interface language",
    "settings.about": "About",
    "settings.aboutHint": "Version and updates",
    "language.eyebrow": "LANGUAGE",
    "language.title": "Interface language",
    "language.description": "Changes apply to the entire interface immediately. No restart required.",
    "language.groupLabel": "Interface language",
    "language.zhCNHint": "Simplified Chinese interface",
    "language.zhTWHint": "Traditional Chinese interface",
    "language.enHint": "English interface",
    "language.jaHint": "Japanese interface",
    "appearance.eyebrow": "APPEARANCE",
    "appearance.title": "Appearance",
    "appearance.description": "The theme applies to Home, Agents, Usage, and every Settings page.",
    "appearance.groupLabel": "Interface theme",
    "appearance.light": "Light",
    "appearance.lightHint": "Always use the light interface",
    "appearance.dark": "Dark",
    "appearance.darkHint": "Always use the dark interface",
    "appearance.system": "System",
    "appearance.systemHint": "The system is currently using {theme}",
    "appearance.systemLight": "light mode",
    "appearance.systemDark": "dark mode",
    "agentVisibility.title": "Agent visibility",
    "agentVisibility.description": "Choose which Agents appear on Home. Undetected Agents are off by default.",
    "agentVisibility.count": "{visible} / {total} visible",
    "agentVisibility.groupLabel": "Agent visibility options",
    "agentVisibility.empty": "The current Registry has no Agents available to show.",
    "key.eyebrow": "LOCAL AUTH",
    "key.title": "Virtual API key",
    "key.description": "Lets local Agents access Token Station. Hidden by default; copying never requires revealing it.",
    "key.authTitle": "API key authentication",
    "key.authSettingsDescription": "Control whether local Agent requests must include the virtual API key.",
    "key.generated": "Generated",
    "key.proxyStopped": "Proxy stopped",
    "key.ariaLabel": "Virtual API key",
    "key.startToGenerate": "Start the proxy to generate",
    "key.hide": "Hide",
    "key.show": "Show for 15s",
    "key.copied": "Copied",
    "key.copy": "Copy",
    "general.title": "Proxy and data",
    "general.description": "Configure local metrics and explicit egress policy.",
    "general.saved": "Saved",
    "general.savedRestart": "Saved · restart the proxy to apply",
    "general.auth": "Virtual key authentication",
    "general.authDescription": "When enabled, the first serve start generates a virtual key and every request must include it. Disabling auth leaves the loopback port unprotected; use only in a trusted local environment.",
    "general.egress": "Egress policy",
    "general.egressDescription": "Explicitly choose direct, HTTP CONNECT, or SOCKS5. System HTTP_PROXY / ALL_PROXY values are never read.",
    "general.egressMode": "Egress mode",
    "general.direct": "Direct",
    "general.proxyUrl": "Proxy URL",
    "general.noProxy": "no_proxy",
    "general.proxyUsername": "Proxy username",
    "general.authSlot": "Credential slot",
    "general.authSlotLabel": "Proxy credential slot",
    "general.credentialCommand": "Store credential: token-station-cli key set egress-proxy {slot}",
    "general.routeSummary": "Provider requests, model catalogs, and health probes: {route}. Update checks always connect directly. 3xx redirects remain blocked and the original Authorization header is never forwarded across hosts.",
    "general.resolvedRoutes": "Resolved egress routes",
    "general.pendingProxy": "proxy URL required",
    "general.matchedNoProxy": "matched no_proxy",
    "general.metrics": "Local metrics",
    "general.metricsDescription": "Write request metadata (latency, tokens, and archival status—never prompt content) to local SQLite for aggregation on the Usage page.",
    "general.save": "Save",
    "general.restartHint": "Proxy is running—restart it after saving to apply changes",
    "general.listen": "Listen address",
    "general.dataDir": "Data directory",
    "general.pluginsDir": "Plugins directory",
    "general.adapter": "Inbound adapter",
    "general.coreVersion": "Core version",
    "runtime.title": "Runtime information",
    "runtime.description": "View the active listen address, data locations, and loaded runtime components.",
    "about.title": "About · Updates",
    "about.description": "Check releases anonymously only when you ask. A signed update can then be downloaded, installed, and restarted in the app.",
    "about.productDescription": "The local model-request routing station for AI agents.",
    "about.versionGroup": "Application versions",
    "about.source": "GitHub",
    "about.releases": "Changelog",
    "about.trustTitle": "How an update reaches this device",
    "about.trustDescription": "The update path stays explicit and verifiable while minimizing disruption to local requests.",
    "about.onDemandTitle": "On-demand check",
    "about.onDemandDescription": "The app contacts the release service anonymously only after you ask.",
    "about.signedTitle": "Signature verification",
    "about.signedDescription": "A download must pass the built-in public-key check before installation.",
    "about.gatewayTitle": "Controlled handoff",
    "about.gatewayDescription": "The gateway briefly stops and drains in-flight requests, then the app restarts.",
    "about.currentVersion": "Current version",
    "about.newVersion": "Version {latest} is available (current: {current}).",
    "about.latest": "Up to date ({current}; latest release: {latest}).",
    "about.copied": "Copied",
    "about.copyLink": "Copy link",
    "about.checking": "Checking…",
    "about.check": "Check for updates",
    "about.updateFound": "Version {version} is available",
    "about.releaseDate": "Released: {date}",
    "about.installVersion": "Download and update to {version}",
    "about.installing": "Verifying and installing…",
    "about.downloaded": "Downloaded {percent}%",
    "about.downloadedBytes": "Downloaded {downloaded} bytes",
    "about.downloadProgress": "Update download progress",
    "about.restarting": "Update installed. Restarting…",
    "about.confirmTitle": "Install app update?",
    "about.confirmDescription": "The update is verified before installation. During the final install, the local gateway briefly stops and drains in-flight requests, then the app restarts.",
    "about.cancel": "Cancel",
    "about.confirmInstall": "Update and restart",
    "plugins.title": "Plugins",
    "plugins.description": "Provider and Agent adapters run in a WASM sandbox with no network access or plaintext keys. Install and develop through the CLI; this view is read-only.",
    "plugins.directory": "Plugins directory",
    "plugins.adapter": "Inbound adapter",
    "plugins.dialects": "Supported dialects",
    "plugins.none": "None",
    "plugins.empty": "(empty)",
    "plugins.refresh": "Refresh",
    "plugins.installHint": "Install: CLI `token-station plugin install <path>`",
    "router.loading": "Loading…",
    "router.unconfigured": "— Not configured —",
    "router.title": "Router · Four layers",
    "router.description": "Each request stops at the first match in this order. Layer 3 counts full-conversation length, turns, code blocks, and capability requirements; difficulty vocabulary reads only the latest user message so repeated history cannot pin every later request to the highest tier.",
    "router.rules": "Rules (hard match)",
    "router.noRules": "No rules. Rules force matching requests into a specific pool.",
    "router.hints": "Hint routing (agent Hint)",
    "router.noHints": "No hint routes. Inbound adapters can route step_type and similar hints here.",
    "router.bands": "Heuristic tiers",
    "router.threshold": "Threshold {value}",
    "router.noBands": "No tiers configured. Choose a provider and model for each tier on Home.",
    "router.score": "Score ≥",
    "router.pool": "Pool",
    "router.target": "Target",
    "router.default": "Default fallback",
    "router.contextWindow": "Assumed context window",
  },
  ja: {
    "nav.main": "メインナビゲーション",
    "nav.homeLabel": "Token Station ホーム",
    "nav.home": "ホーム",
    "nav.scanning": "スキャン中",
    "nav.rescan": "再スキャン",
    "nav.usage": "使用量",
    "nav.settings": "設定",
    "nav.addProvider": "プロバイダーを追加",
    "serve.unknown": "実行状態不明",
    "serve.running": "プロキシ実行中",
    "serve.starting": "起動中",
    "serve.stopping": "停止中",
    "serve.retry": "起動を再試行",
    "serve.startProxy": "プロキシを起動",
    "serve.agent": "Agent",
    "serve.connected": "接続済み",
    "serve.disconnected": "未接続",
    "serve.stop": "停止",
    "serve.cancel": "キャンセル",
    "serve.stoppingShort": "停止中",
    "serve.start": "起動",
    "settings.controlRoom": "CONTROL ROOM",
    "settings.title": "設定",
    "settings.navLabel": "設定カテゴリー",
    "settings.general": "プロキシ",
    "settings.generalHint": "プロキシ、指標、送信ポリシー",
    "settings.apiKey": "API Key",
    "settings.apiKeyHint": "ローカル Agent のアクセス認証情報",
    "settings.agentVisibility": "Agent 表示",
    "settings.agentVisibilityHint": "ホームの Agent 一覧",
    "settings.router": "ルーター",
    "settings.routerHint": "読み取り専用の判断構造",
    "settings.plugins": "プラグイン",
    "settings.pluginsHint": "読み込み済み機能",
    "settings.appearance": "外観",
    "settings.appearanceHint": "ライト・ダークテーマ",
    "settings.language": "言語",
    "settings.languageHint": "表示言語",
    "settings.about": "このアプリについて",
    "settings.aboutHint": "バージョンと更新",
    "language.eyebrow": "LANGUAGE",
    "language.title": "表示言語",
    "language.description": "変更はインターフェース全体にすぐ反映されます。再起動は不要です。",
    "language.groupLabel": "表示言語",
    "language.zhCNHint": "簡体字中国語の画面",
    "language.zhTWHint": "繁体字中国語の画面",
    "language.enHint": "英語の画面",
    "language.jaHint": "日本語の画面",
    "appearance.eyebrow": "APPEARANCE",
    "appearance.title": "外観",
    "appearance.description": "テーマはホーム、Agent、使用量、すべての設定画面に適用されます。",
    "appearance.groupLabel": "インターフェーステーマ",
    "appearance.light": "ライト",
    "appearance.lightHint": "常に明るい画面を使用",
    "appearance.dark": "ダーク",
    "appearance.darkHint": "常に暗い画面を使用",
    "appearance.system": "システム",
    "appearance.systemHint": "現在のシステムは{theme}です",
    "appearance.systemLight": "ライトモード",
    "appearance.systemDark": "ダークモード",
    "agentVisibility.title": "Agent 表示",
    "agentVisibility.description": "ホームに表示する Agent を選びます。未検出の Agent は既定でオフです。",
    "agentVisibility.count": "{visible} / {total} 表示中",
    "agentVisibility.groupLabel": "Agent 表示オプション",
    "agentVisibility.empty": "現在の Registry には表示できる Agent がありません。",
    "key.eyebrow": "LOCAL AUTH",
    "key.title": "仮想 API キー",
    "key.description": "ローカル Agent が Token Station にアクセスするためのキーです。通常は非表示で、表示せずにコピーできます。",
    "key.authTitle": "API Key 認証",
    "key.authSettingsDescription": "ローカル Agent のリクエストに仮想 API Key を必須とするかを制御します。",
    "key.generated": "生成済み",
    "key.proxyStopped": "プロキシ停止中",
    "key.ariaLabel": "仮想 API キー",
    "key.startToGenerate": "プロキシ起動後に生成",
    "key.hide": "隠す",
    "key.show": "15秒間表示",
    "key.copied": "コピー済み",
    "key.copy": "コピー",
    "general.title": "プロキシとデータ",
    "general.description": "ローカル指標と明示的な送信ポリシーを設定します。",
    "general.saved": "保存しました",
    "general.savedRestart": "保存しました · プロキシの再起動後に反映",
    "general.auth": "仮想 Key 認証",
    "general.authDescription": "有効にすると、serve の初回起動時に仮想 Key が生成され、すべてのリクエストに Key が必要になります。無効にするとループバックポートが保護されないため、信頼できるローカル環境でのみ使用してください。",
    "general.egress": "送信ポリシー",
    "general.egressDescription": "直接接続、HTTP CONNECT、SOCKS5 を明示的に選択します。システムの HTTP_PROXY / ALL_PROXY は読み取りません。",
    "general.egressMode": "送信モード",
    "general.direct": "直接接続",
    "general.proxyUrl": "プロキシ URL",
    "general.noProxy": "no_proxy",
    "general.proxyUsername": "プロキシユーザー名",
    "general.authSlot": "認証スロット",
    "general.authSlotLabel": "プロキシ認証スロット",
    "general.credentialCommand": "認証情報を保存：token-station-cli key set egress-proxy {slot}",
    "general.routeSummary": "Provider リクエスト、モデルカタログ、ヘルスチェック：{route}。更新確認は常に直接接続です。3xx リダイレクトには追従せず、元の Authorization を別ホストへ転送しません。",
    "general.resolvedRoutes": "実際の送信経路",
    "general.pendingProxy": "プロキシ URL が必要",
    "general.matchedNoProxy": "no_proxy に一致",
    "general.metrics": "ローカル指標",
    "general.metricsDescription": "各リクエストのメタデータ（遅延、token、保存状態。prompt 内容は含みません）をローカル SQLite に保存し、「使用量」ページで集計します。",
    "general.save": "保存",
    "general.restartHint": "プロキシ実行中——保存後に再起動すると反映されます",
    "general.listen": "待受アドレス",
    "general.dataDir": "データディレクトリ",
    "general.pluginsDir": "プラグインディレクトリ",
    "general.adapter": "受信アダプター",
    "general.coreVersion": "コアバージョン",
    "runtime.title": "実行情報",
    "runtime.description": "現在の待受アドレス、データの場所、読み込まれた実行コンポーネントを確認します。",
    "about.title": "このアプリについて · 更新",
    "about.description": "操作したときだけ最新リリースを匿名で確認します。署名検証後、アプリ内でダウンロード、インストール、再起動できます。",
    "about.productDescription": "ローカル AI Agent 向けのモデルリクエストルーティングステーションです。",
    "about.versionGroup": "アプリケーションのバージョン",
    "about.source": "GitHub",
    "about.releases": "変更履歴",
    "about.trustTitle": "更新がこのデバイスに届くまで",
    "about.trustDescription": "更新経路を明示して検証可能にし、ローカルリクエストへの影響を最小限に抑えます。",
    "about.onDemandTitle": "オンデマンド確認",
    "about.onDemandDescription": "確認を要求した場合にのみ、アプリはリリースサービスへ匿名で接続します。",
    "about.signedTitle": "署名検証",
    "about.signedDescription": "ダウンロードした更新は、インストール前に内蔵公開鍵による検証に合格する必要があります。",
    "about.gatewayTitle": "制御された切り替え",
    "about.gatewayDescription": "ゲートウェイを短時間停止して処理中のリクエストを排出した後、アプリを再起動します。",
    "about.currentVersion": "現在のバージョン",
    "about.newVersion": "新しいバージョン {latest} があります（現在：{current}）。",
    "about.latest": "最新版です（{current}、最新リリース：{latest}）。",
    "about.copied": "コピー済み",
    "about.copyLink": "リンクをコピー",
    "about.checking": "確認中…",
    "about.check": "更新を確認",
    "about.updateFound": "新しいバージョン {version} があります",
    "about.releaseDate": "公開日：{date}",
    "about.installVersion": "{version} をダウンロードして更新",
    "about.installing": "検証してインストール中…",
    "about.downloaded": "{percent}% ダウンロード済み",
    "about.downloadedBytes": "{downloaded} バイトをダウンロード済み",
    "about.downloadProgress": "アップデートのダウンロード進捗",
    "about.restarting": "更新完了。再起動中…",
    "about.confirmTitle": "アプリの更新をインストールしますか？",
    "about.confirmDescription": "更新パッケージはインストール前に署名検証されます。最終インストール時にローカルゲートウェイを一時停止して処理中のリクエストを排出し、その後アプリを再起動します。",
    "about.cancel": "キャンセル",
    "about.confirmInstall": "更新して再起動",
    "plugins.title": "プラグイン",
    "plugins.description": "Provider / Agent アダプターは、ネットワークや平文 Key にアクセスできない WASM サンドボックスで動作します。インストールと開発は CLI で行い、ここでは読み取りのみ可能です。",
    "plugins.directory": "プラグインディレクトリ",
    "plugins.adapter": "受信アダプター",
    "plugins.dialects": "対応方言",
    "plugins.none": "なし",
    "plugins.empty": "（空）",
    "plugins.refresh": "更新",
    "plugins.installHint": "インストール：CLI `token-station plugin install <パス>`",
    "router.loading": "読み込み中…",
    "router.unconfigured": "— 未設定 —",
    "router.title": "ルーター · 4 レイヤー",
    "router.description": "各リクエストはこの順序で最初に一致した時点で停止します。第 3 レイヤーは会話全体の長さ、ターン数、コードブロック、能力要件を数えます。難易度語彙だけは最新のユーザーメッセージを対象にし、履歴の反復で以後の全リクエストが最高ティアに固定されるのを防ぎます。",
    "router.rules": "ルール（完全一致）",
    "router.noRules": "ルールはありません。ルールは特定条件のリクエストを指定プールへ強制します。",
    "router.hints": "ヒントルーティング（agent Hint）",
    "router.noHints": "ヒントルートはありません。受信アダプターの step_type などの Hint はここで振り分けられます。",
    "router.bands": "ヒューリスティックティア",
    "router.threshold": "しきい値 {value}",
    "router.noBands": "ティアが未設定です。ホームで各ティアのプロバイダーとモデルを選択してください。",
    "router.score": "スコア ≥",
    "router.pool": "プール",
    "router.target": "ターゲット",
    "router.default": "デフォルトフォールバック",
    "router.contextWindow": "想定コンテキストウィンドウ",
  },
} as const;

export type TranslationKey = keyof (typeof messages)["zh-CN"];

type Replacements = Record<string, string | number>;

export type LocalizedCopy = (
  english: string,
  simplifiedChinese: string,
  traditionalChinese: string,
  japanese: string,
) => string;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey, replacements?: Replacements) => string;
  copy: LocalizedCopy;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

function isLanguage(value: string | null): value is Language {
  return value === "zh-CN" || value === "zh-TW" || value === "en" || value === "ja";
}

function detectedLanguage(): Language {
  if (typeof window === "undefined") return "en";
  try {
    const locales = window.navigator.languages.length > 0
      ? window.navigator.languages
      : [window.navigator.language];
    for (const locale of locales) {
      const parts = locale.replace(/_/g, "-").toLocaleLowerCase().split("-");
      if (parts[0] === "en") return "en";
      if (parts[0] === "ja") return "ja";
      if (parts[0] === "zh") {
        if (parts.includes("hant")) return "zh-TW";
        if (parts.includes("hans")) return "zh-CN";
        if (parts.includes("tw") || parts.includes("hk") || parts.includes("mo")) return "zh-TW";
        if (
          parts.length === 1
          || parts.includes("cn")
          || parts.includes("sg")
        ) return "zh-CN";
      }
    }
  } catch {
    // Locale detection is best-effort; English remains the safe complete fallback.
  }
  return "en";
}

function storedLanguage(): Language {
  if (typeof window === "undefined") return "en";
  try {
    const value = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (value === "zh") return "zh-CN";
    return isLanguage(value) ? value : detectedLanguage();
  } catch {
    return detectedLanguage();
  }
}

function format(message: string, replacements?: Replacements): string {
  if (!replacements) return message;
  return message.replace(/\{(\w+)\}/g, (match, key: string) =>
    replacements[key] == null ? match : String(replacements[key]));
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { showError } = useErrorToast();
  const [language, setLanguage] = useState<Language>(storedLanguage);

  useEffect(() => {
    try {
      window.localStorage.setItem(LANGUAGE_PREFERENCE_VERSION_KEY, LANGUAGE_PREFERENCE_VERSION);
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    } catch {
      showError(
        {
          "zh-CN": "语言已在本次会话生效，但无法保存到下次启动。",
          "zh-TW": "語言已在本次工作階段生效，但無法儲存供下次啟動使用。",
          en: "The language changed for this session, but it could not be saved for the next launch.",
          ja: "言語は今回のセッションに反映されましたが、次回の起動用に保存できませんでした。",
        }[language],
        "language-storage",
      );
    }
  }, [language, showError]);

  useLayoutEffect(() => {
    setActiveLanguage(language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      t: (key, replacements) => format(messages[language][key], replacements),
      copy: (english, simplifiedChinese, traditionalChinese, japanese) => localizedCopy(
        language,
        english,
        simplifiedChinese,
        traditionalChinese,
        japanese,
      ),
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function LanguageBoundary({ children }: { children: ReactNode }) {
  const value = useContext(LanguageContext);
  return value ? children : <LanguageProvider>{children}</LanguageProvider>;
}

export function useLanguage(): LanguageContextValue {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used within LanguageProvider");
  return value;
}

export function useLocalizedCopy(): Pick<LanguageContextValue, "language" | "copy"> {
  const value = useContext(LanguageContext);
  const language = storedLanguage();
  return value ?? {
    language,
    copy: (english, simplifiedChinese, traditionalChinese, japanese) => localizedCopy(
      language,
      english,
      simplifiedChinese,
      traditionalChinese,
      japanese,
    ),
  };
}
